# Generated by Django 2.0.7 on 2018-07-25 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Категорія')),
            ],
            options={
                'verbose_name_plural': 'Категорії ресурсів',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Кількість')),
                ('date_recomended', models.DateField(verbose_name='Дата рекомендована')),
                ('date_real', models.DateField(verbose_name='Дата реальна')),
            ],
            options={
                'verbose_name_plural': 'Поставка',
            },
        ),
        migrations.CreateModel(
            name='DeliveryDetalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Кількість')),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Delivery', verbose_name='Доставка')),
            ],
            options={
                'verbose_name_plural': 'Деталі поставки',
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(auto_now_add=True, verbose_name='Дата початку')),
                ('date_finish', models.DateField(verbose_name='Дата закінчення')),
            ],
            options={
                'verbose_name_plural': 'Зайнятість',
            },
        ),
        migrations.CreateModel(
            name='GeographyPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Географічні точки',
            },
        ),
        migrations.CreateModel(
            name='KindOfTransport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('category', models.CharField(max_length=30, verbose_name='Категорія')),
                ('speed', models.IntegerField(verbose_name='Максимальна швидкість')),
                ('expences_fuel', models.IntegerField(verbose_name='Витрати пального')),
                ('volume_transport', models.FloatField(verbose_name='Об"єм')),
                ('max_weight', models.IntegerField(verbose_name='Грузопід"ємніcть')),
                ('passability', models.FloatField(verbose_name='Проходимість')),
            ],
            options={
                'verbose_name_plural': 'Вид транспорту',
            },
        ),
        migrations.CreateModel(
            name='MakingRoat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True, verbose_name='Номер по порядку')),
            ],
            options={
                'verbose_name_plural': 'Створення маршруту',
            },
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Кількість ресурсу')),
                ('finished', models.BooleanField(default=False)),
                ('priority', models.IntegerField(null=True, verbose_name='Пріорітет')),
                ('date_recomended', models.DateField(null=True, verbose_name='Дата рекомендованої доставки')),
            ],
            options={
                'verbose_name_plural': 'Потреба',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Назва')),
                ('date_order', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.CreateModel(
            name='Perfomance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Кількість')),
                ('date', models.DateField(verbose_name='Дата виконання')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Need', verbose_name='Потреба')),
            ],
            options={
                'verbose_name_plural': 'Виконання',
            },
        ),
        migrations.CreateModel(
            name='PointOfConsuming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, verbose_name='ПІБ заказника')),
                ('telephone', models.CharField(max_length=20, verbose_name='Телефон заказника')),
                ('geography_point', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.GeographyPoint', verbose_name='Географічна точка')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_consuming', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Споживач',
            },
        ),
        migrations.CreateModel(
            name='Potential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('Кожного разу', 'Кожного разу'), ('Кожної неділі', 'Кожної неділі'), ('Кожного місяця', 'Кожного місяця')], max_length=30, verbose_name='Періодичність')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CategoryResource', verbose_name='Категорія')),
            ],
            options={
                'verbose_name_plural': 'Потенціал',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Назва ресурсу')),
                ('unit_of_mesure', models.CharField(max_length=30, verbose_name='Одиниця виміру')),
                ('weight_one_unit', models.FloatField(null=True, verbose_name='Маса однієї одиниці')),
                ('volume_of_one_unit', models.FloatField(verbose_name='Об"єм однієї одиниці')),
                ('price_one_unit', models.FloatField(verbose_name='Ціна однієї одиниці')),
                ('category_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CategoryResource', verbose_name='Категорія ресурса')),
            ],
            options={
                'verbose_name_plural': 'Ресурси',
            },
        ),
        migrations.CreateModel(
            name='ResourceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Кількість ресурсу')),
                ('finished', models.BooleanField(default=False, verbose_name='Виконано:')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('date_finished', models.DateTimeField(verbose_name='Дата повного виконання')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Resource', verbose_name='Потрібний ресурс')),
            ],
            options={
                'verbose_name_plural': 'Замовлення ресурсів',
            },
        ),
        migrations.CreateModel(
            name='Roat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('point_consuming', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PointOfConsuming', verbose_name='До пункту')),
            ],
            options={
                'verbose_name_plural': 'Маршрут',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recomended', models.DateField(verbose_name='Дата відгрузки')),
            ],
            options={
                'verbose_name_plural': 'Відгрузка',
            },
        ),
        migrations.CreateModel(
            name='ShippingDetalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Кількість')),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shipping', verbose_name='Відгрузка')),
            ],
            options={
                'verbose_name_plural': 'Деталізація відгрузки',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True, verbose_name='Кількість одиниць ресурсу')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Resource', verbose_name='Ресурс')),
            ],
            options={
                'verbose_name_plural': 'Запас',
            },
        ),
        migrations.CreateModel(
            name='StoreHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(verbose_name='Об"єм складу')),
                ('rent', models.IntegerField(verbose_name='Ціна за м^2')),
                ('free_volume', models.FloatField(blank=True, null=True, verbose_name='Вільний об"єм')),
                ('geography_point', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.GeographyPoint', verbose_name='Географічна точка')),
            ],
            options={
                'verbose_name_plural': 'Склади',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Держ. номер')),
                ('kind_of_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.KindOfTransport', verbose_name='Вид автомобіля')),
            ],
            options={
                'verbose_name_plural': 'Транспорт',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(auto_now_add=True, verbose_name='Дата початку')),
                ('perfomance', models.BooleanField(default=False, verbose_name='Виконаність')),
                ('roat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Roat', verbose_name='Маршрут')),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Shipping', verbose_name='Відгрузка')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Transport', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name_plural': 'Поїздка',
            },
        ),
        migrations.CreateModel(
            name='Volonter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ПІБ')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('address', models.CharField(choices=[('Вінницька область', 'Вінницька область'), ('Волинська область', 'Волинська область'), ('Дніпропетровська область', 'Дніпропетровська область'), ('Донецька область', 'Донецька область'), ('Закарпатська область', 'Закарпатська область'), ('Запорізька область', 'Запорізька область'), ('Івано-Франківська область', 'Івано-Франківська область'), ('Київська область', 'Київська область'), ('Кіровоградська область', 'Кіровоградська область'), ('Луганська область', 'Луганська область'), ('Львівська область', 'Львівська область'), ('Миколаївська область', 'Миколаївська область'), ('Одеська область', 'Одеська область'), ('Полтавська область', 'Полтавська область'), ('Рівненська область', 'Рівненська область'), ('Сумська область', 'Сумська область'), ('Тернопільська область', 'Тернопільська область'), ('Харківська область', 'Харківська область'), ('Херсонська область', 'Херсонська область'), ('Хмельницька область', 'Хмельницька область'), ('Черкаська область', 'Черкаська область'), ('Чернігівська область', 'Чернігівська область'), ('Чернівецька область', 'Чернівецька область'), ('Автономна Республіка Крим', 'Автономна Республіка Крим')], max_length=30, verbose_name='Область проживання')),
                ('telephone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('gender', models.CharField(choices=[('М', 'Male'), ('Ж', 'Female')], max_length=1, verbose_name='Стать')),
                ('activeted', models.BooleanField(default=False, verbose_name='Підтвердження')),
                ('categories', models.ManyToManyField(to='main.CategoryResource', verbose_name='Категорія ресурсів')),
            ],
            options={
                'verbose_name_plural': 'Волонтери',
            },
        ),
        migrations.CreateModel(
            name='Way',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roat_length', models.IntegerField(verbose_name='Довжина')),
                ('danger', models.FloatField(verbose_name='Небезпечність')),
                ('passability', models.IntegerField(verbose_name='Проходимість')),
                ('load', models.IntegerField(verbose_name='Заповненість')),
                ('yandex_or_byhand', models.BooleanField(choices=[(True, 'Яндекс'), (False, 'Вручну')], default=True, verbose_name='Вид створення доріг')),
                ('point_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_from', to='main.GeographyPoint', verbose_name='Звідки')),
                ('point_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_to', to='main.GeographyPoint', verbose_name='Куди')),
            ],
            options={
                'verbose_name_plural': 'Дороги',
            },
        ),
        migrations.AddField(
            model_name='stock',
            name='store_house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.StoreHouse', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='shippingdetalization',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Stock', verbose_name='Запас'),
        ),
        migrations.AddField(
            model_name='roat',
            name='storehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.StoreHouse', verbose_name='Від складу'),
        ),
        migrations.AddField(
            model_name='roat',
            name='transport',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Transport', verbose_name='Рекомендований транспортний засіб'),
        ),
        migrations.AddField(
            model_name='roat',
            name='wasys',
            field=models.ManyToManyField(blank=True, to='main.Way', verbose_name='Проміжні дороги'),
        ),
        migrations.AddField(
            model_name='potential',
            name='volonter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Volonter', verbose_name='Волонтер'),
        ),
        migrations.AddField(
            model_name='order',
            name='point_consuming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PointOfConsuming', verbose_name='Точка споживання'),
        ),
        migrations.AddField(
            model_name='need',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Order', verbose_name='Замовлення'),
        ),
        migrations.AddField(
            model_name='need',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Resource', verbose_name='Потрібний ресурс'),
        ),
        migrations.AddField(
            model_name='makingroat',
            name='roat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Roat', verbose_name='Маршрут'),
        ),
        migrations.AddField(
            model_name='makingroat',
            name='way',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Way', verbose_name='Дорога'),
        ),
        migrations.AddField(
            model_name='employment',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Transport', verbose_name='Транспорт'),
        ),
        migrations.AddField(
            model_name='deliverydetalization',
            name='storehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StoreHouse', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Resource', verbose_name='Ресурс'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='volonter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Volonter', verbose_name='Волонтер'),
        ),
    ]
